import "./globals.css";

import { Navigation } from "@/features/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <main className="flex flex-col items-center min-h-screen pb-16 dark:bg-neutral-950 dark:text-neutral-200">
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
