import "./globals.css";

import { Inter } from "next/font/google";
import { Navigation } from "@/features/navigation";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} dark`}>
      <body>
        <main className="flex flex-col items-center min-h-screen pb-16 dark:bg-neutral-950 dark:text-neutral-200">
          <Navigation />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
